name: Docker Image CI

on:
  push:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Build the Docker image
        run: docker build -t nshmp-haz .
