name: Build nshmp-haz JAR

on:
  push:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      -
        name: Build with Gradle
        run: ./gradlew build
      -
        name: Test nshmp-haz
        run: |
          java -cp build/libs/nshmp-haz.jar \
            gov.usgs.earthquake.nshmp.HazardCalc \
            etc/peer/models/Set1-Case1 \
            "Test Site, -122.0, 38.0"
